### ISSUE TITLE
modelbase version

### ISSUE THREAD

**Issue by steve-rolfe** [QTB-HHU/photosynthesismodel#1]
Hi
I'm trying to run the photoynthesismodel. The online Jupyter link gives an error (no GLIDMA module).
I've downloaded everything to a local Jupyter version and get an error module 'modelbase' has no attribute 'Model'

I installed modelbase in a conda environment as recommended.
I see at https://gitlab.com/qtb-hhu/modelbase-software that there are version differences
In a paper describing modelbase, it's stated that v1.26 was used for photosynthetic modelling. I tried the oldest version on conda (v1.3.8) but this didn't help.

Could you tell me please which modelbase version I should use and where I might find it?
Thanks for providing this excellent resource.
Best wishes
Steve Rolfe

**Comment by steve-rolfe** [comment]
For anyone checking, I got things to work with modelbase 0.2.5
I did this via a pip install as the conda versions don't seem to go that far back
